using IronPython.Hosting;
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Scripting.Hosting;
using System.Diagnostics;
using System.IO;

namespace FlightsEngine.FlighsBot
{
    public static class PythonHelper
    {
        public static void run()
        {
            System.Diagnostics.Process cmd = new System.Diagnostics.Process();
            try
            {
                // https://stackoverflow.com/questions/1469764/run-command-prompt-commands

                string cmdPath = @"D:\DEV\Batch1\WebScraper\Main.py";
                string pythonExe= @"C:\Users\franc\AppData\Local\Programs\Python\Python37-32\python.exe";
                string args= "\"213.192.33.229:21776 CZ-H-S + \" \"1\" \"Edreams\" \"RNS\" \"TYO\" \"false\" \"10/10/2018\" \"18/10/2018\"";

                Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + " ***  START Python Helper ***");

                System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
                startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
                startInfo.FileName = "cmd.exe";
                startInfo.Arguments = string.Format("/C {0} {1} {2}", pythonExe, cmdPath, args);

                cmd.StartInfo.RedirectStandardInput = true;
                cmd.StartInfo.RedirectStandardOutput = true;
                cmd.StartInfo.CreateNoWindow = false;
                cmd.StartInfo.UseShellExecute = false;;
                /*
                start.UseShellExecute = false;// Do not use OS shell
                start.CreateNoWindow = true; // We don't need new window
                start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
                start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
                */
                cmd.StartInfo = startInfo;
                cmd.Start();

              //  cmd.StandardInput.WriteLine("echo Oscar");
              //  cmd.StandardInput.Flush();
              //  cmd.StandardInput.Close();
             //   cmd.WaitForExit();
                Console.WriteLine(cmd.StandardOutput.ReadToEnd());

                Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + " ***  END Python Helper ***");
            }
            catch(Exception e)
            {
                FlightsEngine.Utils.Logger.GenerateError(e, System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, null);
            }
            finally
            {
                cmd.Close();
            }
        }

    }
}